version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-alpine
    working_directory: /go/src/github.com/jniedrauer/dynamic-security-groups

    steps:
      - checkout

      - restore_cache:
          keys:
            - mod-{{ checksum "go.sum" }}

      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test
      - run:
          name: Build
          command: make

      - save_cache:
          key: mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"

      - store_test_results:
          path: /go/src/github.com/jniedrauer/dynamic-security-groups/build/test-reports
